---
- name: Create technical user
  hosts: ci_cd_server
  roles:
  - role: vm

- name: Install drone ci/cd
  hosts: ci_cd_server
  become: true
  #become_user: "{{ ci_cd_user }}"
  roles:
  - role: drone
